'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace OPCDA1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Tgs", [Namespace]:="http://schemas.datacontract.org/2004/07/OpcDaWindowsService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Tgs
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TgNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fullpathField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TgName() As String
            Get
                Return Me.TgNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TgNameField, value) <> true) Then
                    Me.TgNameField = value
                    Me.RaisePropertyChanged("TgName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fullpath() As String
            Get
                Return Me.fullpathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fullpathField, value) <> true) Then
                    Me.fullpathField = value
                    Me.RaisePropertyChanged("fullpath")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OPCDA1.IOpcDaWcfSer")>  _
    Public Interface IOpcDaWcfSer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValue", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValueResponse")>  _
        Function GetOPCValue(ByVal TagName() As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValue", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValueResponse")>  _
        Function GetOPCValueAsync(ByVal TagName() As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/ConnectToOPC", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/ConnectToOPCResponse")>  _
        Sub ConnectToOPC()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/ConnectToOPC", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/ConnectToOPCResponse")>  _
        Function ConnectToOPCAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCServerName", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCServerNameResponse")>  _
        Function GetOPCServerName() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCServerName", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCServerNameResponse")>  _
        Function GetOPCServerNameAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValues", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesResponse")>  _
        Function GetOPCValues(ByVal TagName() As String, ByVal UTCTime As Long) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValues", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesResponse")>  _
        Function GetOPCValuesAsync(ByVal TagName() As String, ByVal UTCTime As Long) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesByTagsTime", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesByTagsTimeResponse")>  _
        Function GetOPCValuesByTagsTime(ByVal TagName() As String, ByVal UTCTime() As Long) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesByTagsTime", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCValuesByTagsTimeResponse")>  _
        Function GetOPCValuesByTagsTimeAsync(ByVal TagName() As String, ByVal UTCTime() As Long) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/WriteOPCValue", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/WriteOPCValueResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Long())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OPCDA1.Tgs())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OPCDA1.Tgs))>  _
        Function WriteOPCValue(ByVal TagName As String, ByVal TagValue As Object) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/WriteOPCValue", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/WriteOPCValueResponse")>  _
        Function WriteOPCValueAsync(ByVal TagName As String, ByVal TagValue As Object) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCTags", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCTagsResponse")>  _
        Function GetOPCTags() As OPCDA1.Tgs()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCTags", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCTagsResponse")>  _
        Function GetOPCTagsAsync() As System.Threading.Tasks.Task(Of OPCDA1.Tgs())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/DisconnectOPC", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/DisconnectOPCResponse")>  _
        Sub DisconnectOPC()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/DisconnectOPC", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/DisconnectOPCResponse")>  _
        Function DisconnectOPCAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCStatus", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCStatusResponse")>  _
        Function GetOPCStatus() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/GetOPCStatus", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/GetOPCStatusResponse")>  _
        Function GetOPCStatusAsync() As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/SetDontConnect", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/SetDontConnectResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(String())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Long())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OPCDA1.Tgs())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(OPCDA1.Tgs))>  _
        Function SetDontConnect() As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOpcDaWcfSer/SetDontConnect", ReplyAction:="http://tempuri.org/IOpcDaWcfSer/SetDontConnectResponse")>  _
        Function SetDontConnectAsync() As System.Threading.Tasks.Task(Of Object)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOpcDaWcfSerChannel
        Inherits OPCDA1.IOpcDaWcfSer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OpcDaWcfSerClient
        Inherits System.ServiceModel.ClientBase(Of OPCDA1.IOpcDaWcfSer)
        Implements OPCDA1.IOpcDaWcfSer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetOPCValue(ByVal TagName() As String) As String Implements OPCDA1.IOpcDaWcfSer.GetOPCValue
            Return MyBase.Channel.GetOPCValue(TagName)
        End Function
        
        Public Function GetOPCValueAsync(ByVal TagName() As String) As System.Threading.Tasks.Task(Of String) Implements OPCDA1.IOpcDaWcfSer.GetOPCValueAsync
            Return MyBase.Channel.GetOPCValueAsync(TagName)
        End Function
        
        Public Sub ConnectToOPC() Implements OPCDA1.IOpcDaWcfSer.ConnectToOPC
            MyBase.Channel.ConnectToOPC
        End Sub
        
        Public Function ConnectToOPCAsync() As System.Threading.Tasks.Task Implements OPCDA1.IOpcDaWcfSer.ConnectToOPCAsync
            Return MyBase.Channel.ConnectToOPCAsync
        End Function
        
        Public Function GetOPCServerName() As String Implements OPCDA1.IOpcDaWcfSer.GetOPCServerName
            Return MyBase.Channel.GetOPCServerName
        End Function
        
        Public Function GetOPCServerNameAsync() As System.Threading.Tasks.Task(Of String) Implements OPCDA1.IOpcDaWcfSer.GetOPCServerNameAsync
            Return MyBase.Channel.GetOPCServerNameAsync
        End Function
        
        Public Function GetOPCValues(ByVal TagName() As String, ByVal UTCTime As Long) As String Implements OPCDA1.IOpcDaWcfSer.GetOPCValues
            Return MyBase.Channel.GetOPCValues(TagName, UTCTime)
        End Function
        
        Public Function GetOPCValuesAsync(ByVal TagName() As String, ByVal UTCTime As Long) As System.Threading.Tasks.Task(Of String) Implements OPCDA1.IOpcDaWcfSer.GetOPCValuesAsync
            Return MyBase.Channel.GetOPCValuesAsync(TagName, UTCTime)
        End Function
        
        Public Function GetOPCValuesByTagsTime(ByVal TagName() As String, ByVal UTCTime() As Long) As String Implements OPCDA1.IOpcDaWcfSer.GetOPCValuesByTagsTime
            Return MyBase.Channel.GetOPCValuesByTagsTime(TagName, UTCTime)
        End Function
        
        Public Function GetOPCValuesByTagsTimeAsync(ByVal TagName() As String, ByVal UTCTime() As Long) As System.Threading.Tasks.Task(Of String) Implements OPCDA1.IOpcDaWcfSer.GetOPCValuesByTagsTimeAsync
            Return MyBase.Channel.GetOPCValuesByTagsTimeAsync(TagName, UTCTime)
        End Function
        
        Public Function WriteOPCValue(ByVal TagName As String, ByVal TagValue As Object) As String Implements OPCDA1.IOpcDaWcfSer.WriteOPCValue
            Return MyBase.Channel.WriteOPCValue(TagName, TagValue)
        End Function
        
        Public Function WriteOPCValueAsync(ByVal TagName As String, ByVal TagValue As Object) As System.Threading.Tasks.Task(Of String) Implements OPCDA1.IOpcDaWcfSer.WriteOPCValueAsync
            Return MyBase.Channel.WriteOPCValueAsync(TagName, TagValue)
        End Function
        
        Public Function GetOPCTags() As OPCDA1.Tgs() Implements OPCDA1.IOpcDaWcfSer.GetOPCTags
            Return MyBase.Channel.GetOPCTags
        End Function
        
        Public Function GetOPCTagsAsync() As System.Threading.Tasks.Task(Of OPCDA1.Tgs()) Implements OPCDA1.IOpcDaWcfSer.GetOPCTagsAsync
            Return MyBase.Channel.GetOPCTagsAsync
        End Function
        
        Public Sub DisconnectOPC() Implements OPCDA1.IOpcDaWcfSer.DisconnectOPC
            MyBase.Channel.DisconnectOPC
        End Sub
        
        Public Function DisconnectOPCAsync() As System.Threading.Tasks.Task Implements OPCDA1.IOpcDaWcfSer.DisconnectOPCAsync
            Return MyBase.Channel.DisconnectOPCAsync
        End Function
        
        Public Function GetOPCStatus() As Boolean Implements OPCDA1.IOpcDaWcfSer.GetOPCStatus
            Return MyBase.Channel.GetOPCStatus
        End Function
        
        Public Function GetOPCStatusAsync() As System.Threading.Tasks.Task(Of Boolean) Implements OPCDA1.IOpcDaWcfSer.GetOPCStatusAsync
            Return MyBase.Channel.GetOPCStatusAsync
        End Function
        
        Public Function SetDontConnect() As Object Implements OPCDA1.IOpcDaWcfSer.SetDontConnect
            Return MyBase.Channel.SetDontConnect
        End Function
        
        Public Function SetDontConnectAsync() As System.Threading.Tasks.Task(Of Object) Implements OPCDA1.IOpcDaWcfSer.SetDontConnectAsync
            Return MyBase.Channel.SetDontConnectAsync
        End Function
    End Class
End Namespace
